// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChjJWDgabJPLTQqKT4wZA2LdgVA7Fcr9Y',
    appId: '1:1010218260386:web:383e6cc4adaf4b7c7044fb',
    messagingSenderId: '1010218260386',
    projectId: 'flutterapp-14563',
    authDomain: 'flutterapp-14563.firebaseapp.com',
    storageBucket: 'flutterapp-14563.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBp1b-sSzewFWKqSQGLD-UbUFppEcy19Fk',
    appId: '1:1010218260386:android:61fac96427b9b4217044fb',
    messagingSenderId: '1010218260386',
    projectId: 'flutterapp-14563',
    storageBucket: 'flutterapp-14563.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADYyyZAL7z7armhf8XVwxzZ8tfwLARYZ4',
    appId: '1:1010218260386:ios:22bb31745f3b6b337044fb',
    messagingSenderId: '1010218260386',
    projectId: 'flutterapp-14563',
    storageBucket: 'flutterapp-14563.appspot.com',
    iosBundleId: 'com.example.eferei2023gr109',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyADYyyZAL7z7armhf8XVwxzZ8tfwLARYZ4',
    appId: '1:1010218260386:ios:f48e92771a4b42107044fb',
    messagingSenderId: '1010218260386',
    projectId: 'flutterapp-14563',
    storageBucket: 'flutterapp-14563.appspot.com',
    iosBundleId: 'com.example.eferei2023gr109.RunnerTests',
  );
}
